/** @type {import('eslint').Linter.Config} */
export default {
	name: 'koffeine/eslint',
	linterOptions: {
		reportUnusedDisableDirectives: 'error',
		reportUnusedInlineConfigs: 'error'
	},
	rules: {
		// POSSIBLE PROBLEMS

		'array-callback-return': [ 'error', { allowImplicit: false, checkForEach: false, allowVoid: false } ],
		'constructor-super': 'error',
		'for-direction': 'error',
		'getter-return': [ 'error', { allowImplicit: false } ],
		'no-async-promise-executor': 'error',
		'no-await-in-loop': 'error',
		'no-class-assign': 'error',
		'no-compare-neg-zero': 'error',
		'no-cond-assign': [ 'error', 'except-parens' ],
		'no-const-assign': 'error',
		'no-constant-binary-expression': 'error',
		'no-constant-condition': [ 'error', { checkLoops: false } ],
		'no-constructor-return': 'error',
		'no-control-regex': 'error',
		'no-debugger': 'warn',
		'no-dupe-args': 'error',
		'no-dupe-class-members': 'error',
		'no-dupe-else-if': 'error',
		'no-dupe-keys': 'error',
		'no-duplicate-case': 'error',
		'no-duplicate-imports': [ 'error', { includeExports: true, allowSeparateTypeImports: false } ],
		'no-empty-character-class': 'error',
		'no-empty-pattern': 'error',
		'no-ex-assign': 'error',
		'no-fallthrough': [ 'error', { commentPattern: 'break[\\s\\w]*omitted', allowEmptyCase: true, reportUnusedFallthroughComment: true } ],
		'no-func-assign': 'error',
		'no-import-assign': 'error',
		'no-inner-declarations': [ 'error', 'both', { blockScopedFunctions: 'allow' } ],
		'no-invalid-regexp': 'error',
		'no-irregular-whitespace': [ 'error', { skipStrings: false, skipComments: false, skipRegExps: false, skipTemplates: false, skipJSXText: false } ],
		'no-loss-of-precision': 'error',
		'no-misleading-character-class': [ 'error', { allowEscape: true } ],
		'no-new-native-nonconstructor': 'error',
		'no-obj-calls': 'error',
		'no-promise-executor-return': [ 'error', { allowVoid: false } ],
		'no-prototype-builtins': 'error',
		'no-self-assign': [ 'error', { props: true } ],
		'no-self-compare': 'error',
		'no-setter-return': 'error',
		'no-sparse-arrays': 'error',
		'no-template-curly-in-string': 'error',
		'no-this-before-super': 'error',
		'no-unassigned-vars': 'error',
		'no-undef': [ 'error', { typeof: true } ],
		'no-unexpected-multiline': 'error',
		'no-unmodified-loop-condition': 'error',
		'no-unreachable': 'error',
		'no-unreachable-loop': 'error',
		'no-unsafe-finally': 'error',
		'no-unsafe-negation': [ 'error', { enforceForOrderingRelations: true } ],
		'no-unsafe-optional-chaining': [ 'error', { disallowArithmeticOperators: true } ],
		'no-unused-private-class-members': 'error',
		'no-unused-vars': [ 'error', { vars: 'all', args: 'after-used', ignoreRestSiblings: false, caughtErrors: 'all', ignoreClassWithStaticInitBlock: false, reportUsedIgnorePattern: false } ],
		'no-use-before-define': [ 'error', { functions: true, classes: true, variables: true, allowNamedExports: false } ],
		'no-useless-assignment': 'error',
		'no-useless-backreference': 'error',
		'require-atomic-updates': 'off',
		'use-isnan': [ 'error', { enforceForSwitchCase: true, enforceForIndexOf: true } ],
		'valid-typeof': [ 'error', { requireStringLiterals: true } ],

		// SUGGESTIONS

		'accessor-pairs': 'off',
		'arrow-body-style': [ 'error', 'as-needed', { requireReturnForObjectLiteral: false } ],
		'block-scoped-var': 'error',
		'camelcase': [ 'error', { properties: 'always', ignoreDestructuring: false, ignoreImports: false, ignoreGlobals: false } ],
		'capitalized-comments': 'off',
		'class-methods-use-this': 'off',
		'complexity': 'off',
		'consistent-return': [ 'error', { treatUndefinedAsUnspecified: true } ],
		'consistent-this': [ 'error', 'self' ],
		'curly': [ 'error', 'all' ],
		'default-case': 'error',
		'default-case-last': 'error',
		'default-param-last': 'error',
		'dot-notation': [ 'error', { allowKeywords: true } ],
		'eqeqeq': [ 'error', 'smart' ],
		'func-name-matching': [ 'error', 'always', { considerPropertyDescriptor: true, includeCommonJSModuleExports: false } ],
		'func-names': 'off',
		'func-style': [ 'error', 'expression', { allowArrowFunctions: true } ],
		'grouped-accessor-pairs': [ 'error', 'anyOrder' ],
		'guard-for-in': 'off',
		'id-denylist': 'off',
		'id-length': 'off',
		'id-match': 'off',
		'init-declarations': 'off',
		'logical-assignment-operators': [ 'error', 'always', { enforceForIfStatements: true } ],
		'max-classes-per-file': 'off',
		'max-depth': 'off',
		'max-lines': 'off',
		'max-lines-per-function': 'off',
		'max-nested-callbacks': 'off',
		'max-params': 'off',
		'max-statements': 'off',
		'new-cap': [ 'error', { newIsCap: true, capIsNew: true, properties: true } ],
		'no-alert': 'warn',
		'no-array-constructor': 'error',
		'no-bitwise': [ 'error', { int32Hint: false } ],
		'no-caller': 'error',
		'no-case-declarations': 'error',
		'no-console': 'warn',
		'no-continue': 'off',
		'no-delete-var': 'error',
		'no-div-regex': 'off',
		'no-else-return': 'off',
		'no-empty': [ 'error', { allowEmptyCatch: false } ],
		'no-empty-function': 'error',
		'no-empty-static-block': 'error',
		'no-eq-null': 'error',
		'no-eval': [ 'error', { allowIndirect: false } ],
		'no-extend-native': 'error',
		'no-extra-bind': 'error',
		'no-extra-boolean-cast': [ 'error', { enforceForInnerExpressions: true } ],
		'no-extra-label': 'error',
		'no-global-assign': 'error',
		'no-implicit-coercion': [ 'error', { boolean: true, number: true, string: true, disallowTemplateShorthand: true } ],
		'no-implicit-globals': 'off',
		'no-implied-eval': 'error',
		'no-inline-comments': 'off',
		'no-invalid-this': [ 'error', { capIsConstructor: true } ],
		'no-iterator': 'error',
		'no-label-var': 'error',
		'no-labels': [ 'error', { allowLoop: false, allowSwitch: false } ],
		'no-lone-blocks': 'error',
		'no-lonely-if': 'error',
		'no-loop-func': 'error',
		'no-magic-numbers': 'off',
		'no-multi-assign': 'off',
		'no-multi-str': 'error',
		'no-negated-condition': 'error',
		'no-nested-ternary': 'error',
		'no-new': 'error',
		'no-new-func': 'error',
		'no-new-wrappers': 'error',
		'no-nonoctal-decimal-escape': 'error',
		'no-object-constructor': 'error',
		'no-octal': 'error',
		'no-octal-escape': 'error',
		'no-param-reassign': 'off',
		'no-plusplus': 'off',
		'no-proto': 'error',
		'no-redeclare': [ 'error', { builtinGlobals: true } ],
		'no-regex-spaces': 'error',
		'no-restricted-exports': 'off',
		'no-restricted-globals': 'off',
		'no-restricted-imports': 'off',
		'no-restricted-properties': 'off',
		'no-restricted-syntax': 'off',
		'no-return-assign': 'off',
		'no-script-url': 'error',
		'no-sequences': [ 'error', { allowInParentheses: false } ],
		'no-shadow': [ 'error', { builtinGlobals: false, hoist: 'all', ignoreOnInitialization: false } ],
		'no-shadow-restricted-names': [ 'error', { reportGlobalThis: true } ],
		'no-ternary': 'off',
		'no-throw-literal': 'error',
		'no-undef-init': 'error',
		'no-undefined': 'error',
		'no-underscore-dangle': [
			'error',
			{
				allowAfterThis: false,
				allowAfterSuper: false,
				allowAfterThisConstructor: false,
				enforceInMethodNames: true,
				enforceInClassFields: true,
				allowInArrayDestructuring: false,
				allowInObjectDestructuring: false,
				allowFunctionParams: false
			}
		],
		'no-unneeded-ternary': [ 'error', { defaultAssignment: true } ],
		'no-unused-expressions': [ 'error', { allowShortCircuit: false, allowTernary: false, allowTaggedTemplates: false, enforceForJSX: false, ignoreDirectives: false } ],
		'no-unused-labels': 'error',
		'no-useless-call': 'error',
		'no-useless-catch': 'error',
		'no-useless-computed-key': [ 'error', { enforceForClassMembers: true } ],
		'no-useless-concat': 'error',
		'no-useless-constructor': 'error',
		'no-useless-escape': 'error',
		'no-useless-rename': [ 'error', { ignoreImport: false, ignoreExport: false, ignoreDestructuring: false } ],
		'no-useless-return': 'error',
		'no-var': 'error',
		'no-void': [ 'error', { allowAsStatement: false } ],
		'no-warning-comments': [ 'warn', { terms: [ 'todo', 'fixme', 'xxx' ], location: 'start' } ],
		'no-with': 'error',
		'object-shorthand': [ 'error', 'always', { avoidQuotes: false, ignoreConstructors: false, avoidExplicitReturnArrows: true } ],
		'one-var': 'off',
		'operator-assignment': [ 'error', 'always' ],
		'prefer-arrow-callback': [ 'error', { allowNamedFunctions: false, allowUnboundThis: false } ],
		'prefer-const': [ 'error', { destructuring: 'all', ignoreReadBeforeAssign: false } ],
		'prefer-destructuring': 'off',
		'prefer-exponentiation-operator': 'error',
		'prefer-named-capture-group': 'off',
		'prefer-numeric-literals': 'off',
		'prefer-object-has-own': 'error',
		'prefer-object-spread': 'error',
		'prefer-promise-reject-errors': 'off',
		'prefer-regex-literals': 'error',
		'prefer-rest-params': 'error',
		'prefer-spread': 'error',
		'prefer-template': 'error',
		'radix': [ 'error', 'as-needed' ],
		'require-await': 'error',
		'require-unicode-regexp': [ 'error', { requireFlag: 'v' } ],
		'require-yield': 'error',
		'sort-imports': 'off',
		'sort-keys': 'off',
		'sort-vars': 'off',
		'strict': [ 'error', 'global' ],
		'symbol-description': 'off',
		'vars-on-top': 'off',
		'yoda': [ 'error', 'never', { exceptRange: false, onlyEquality: false } ],

		// LAYOUT & FORMATTING

		'unicode-bom': [ 'error', 'never' ]
	}
};
